### PR TITLE
small update translation

### PR DESCRIPTION
**Pull request by Pro-pra**
Товарищи переводчики, возможно так будет более корректно выглядеть

### CODE REVIEW

**Comment by mikhailnov** [comment]
Most changes look useful and good. Is it mandatory to upload changes via weblate?

**Comment by mikhailnov** [comment]
Здесь переводчиков нет, переводчики на Weblate, а этот репозиторйи формируется автоматически из Weblate, насколько понимаю

**Comment by Pro-pra** [comment]
нет

**Comment by jkonecny12** [comment]
Hello, thanks for the PR. We unfortunately don't speak Russian and can't do the review.

However, in general it would be much better to use Weblate for the changes. One reason is that the community around Fedora could react on the change set. Second reason is that there are checks in Weblate which are bypassed by this PR. If it would be too much work for you to put this in by Weblate I guess we are fine to merge the PR, however, I would rather avoid it.

**Comment by jkonecny12** [comment]
This PR seems to be stale. Feel free to re-open it in case you want to get your changes in.

**Pull request closed without merging**
